module.exports = [
  {
    login: 'robertoumbelino',
    id: 17939056,
    node_id: 'MDQ6VXNlcjE3OTM5MDU2',
    avatar_url: 'https://avatars3.githubusercontent.com/u/17939056?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/robertoumbelino',
    html_url: 'https://github.com/robertoumbelino',
    followers_url: 'https://api.github.com/users/robertoumbelino/followers',
    following_url:
      'https://api.github.com/users/robertoumbelino/following{/other_user}',
    gists_url: 'https://api.github.com/users/robertoumbelino/gists{/gist_id}',
    starred_url:
      'https://api.github.com/users/robertoumbelino/starred{/owner}{/repo}',
    subscriptions_url:
      'https://api.github.com/users/robertoumbelino/subscriptions',
    organizations_url: 'https://api.github.com/users/robertoumbelino/orgs',
    repos_url: 'https://api.github.com/users/robertoumbelino/repos',
    events_url: 'https://api.github.com/users/robertoumbelino/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/robertoumbelino/received_events',
    type: 'User',
    site_admin: false,
    name: 'Roberto Umbelino',
    company: 'FW7',
    blog: '',
    location: 'Brazil',
    email: null,
    hireable: null,
    bio: 'Web developer',
    public_repos: 9,
    public_gists: 0,
    followers: 3,
    following: 1,
    created_at: '2016-03-19T02:05:58Z',
    updated_at: '2019-07-22T16:32:22Z'
  },
  {
    login: 'cellobnu',
    id: 5132488,
    node_id: 'MDQ6VXNlcjUxMzI0ODg=',
    avatar_url: 'https://avatars0.githubusercontent.com/u/5132488?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/cellobnu',
    html_url: 'https://github.com/cellobnu',
    followers_url: 'https://api.github.com/users/cellobnu/followers',
    following_url:
      'https://api.github.com/users/cellobnu/following{/other_user}',
    gists_url: 'https://api.github.com/users/cellobnu/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/cellobnu/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/cellobnu/subscriptions',
    organizations_url: 'https://api.github.com/users/cellobnu/orgs',
    repos_url: 'https://api.github.com/users/cellobnu/repos',
    events_url: 'https://api.github.com/users/cellobnu/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/cellobnu/received_events',
    type: 'User',
    site_admin: false,
    name: 'Marcelo Vieira Gonçalves',
    company: 'celobnu.com.br',
    blog: 'http://celobnu.com.br/',
    location: 'Brasil',
    email: null,
    hireable: null,
    bio: null,
    public_repos: 40,
    public_gists: 8,
    followers: 2,
    following: 1,
    created_at: '2013-07-31T20:35:14Z',
    updated_at: '2019-07-22T14:15:04Z'
  },
  {
    login: 'vmarcosp',
    id: 20327229,
    node_id: 'MDQ6VXNlcjIwMzI3MjI5',
    avatar_url: 'https://avatars0.githubusercontent.com/u/20327229?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/vmarcosp',
    html_url: 'https://github.com/vmarcosp',
    followers_url: 'https://api.github.com/users/vmarcosp/followers',
    following_url:
      'https://api.github.com/users/vmarcosp/following{/other_user}',
    gists_url: 'https://api.github.com/users/vmarcosp/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/vmarcosp/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/vmarcosp/subscriptions',
    organizations_url: 'https://api.github.com/users/vmarcosp/orgs',
    repos_url: 'https://api.github.com/users/vmarcosp/repos',
    events_url: 'https://api.github.com/users/vmarcosp/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/vmarcosp/received_events',
    type: 'User',
    site_admin: false,
    name: 'Marcos Oliveira',
    company: null,
    blog: '',
    location: 'Brazil - Blumenau',
    email: null,
    hireable: null,
    bio: 'Front-End Developer and \r\nFounder of @blumenaujs :smile:\r\n',
    public_repos: 54,
    public_gists: 5,
    followers: 69,
    following: 157,
    created_at: '2016-07-06T21:08:30Z',
    updated_at: '2019-06-28T17:12:03Z'
  },
  {
    login: 'MarcelLZ',
    id: 3642745,
    node_id: 'MDQ6VXNlcjM2NDI3NDU=',
    avatar_url: 'https://avatars0.githubusercontent.com/u/3642745?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/MarcelLZ',
    html_url: 'https://github.com/MarcelLZ',
    followers_url: 'https://api.github.com/users/MarcelLZ/followers',
    following_url:
      'https://api.github.com/users/MarcelLZ/following{/other_user}',
    gists_url: 'https://api.github.com/users/MarcelLZ/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/MarcelLZ/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/MarcelLZ/subscriptions',
    organizations_url: 'https://api.github.com/users/MarcelLZ/orgs',
    repos_url: 'https://api.github.com/users/MarcelLZ/repos',
    events_url: 'https://api.github.com/users/MarcelLZ/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/MarcelLZ/received_events',
    type: 'User',
    site_admin: false,
    name: 'Marcel Zanluca',
    company: null,
    blog: 'https://marcelzanluca.com.br',
    location: 'Brasil, Santa Catarina - Blumenau',
    email: null,
    hireable: null,
    bio: 'A developer in a quest for knowledge.',
    public_repos: 21,
    public_gists: 2,
    followers: 19,
    following: 28,
    created_at: '2013-02-20T01:44:37Z',
    updated_at: '2019-03-21T11:34:27Z'
  },
  {
    login: 'viniaxt',
    id: 49204887,
    node_id: 'MDQ6VXNlcjQ5MjA0ODg3',
    avatar_url: 'https://avatars3.githubusercontent.com/u/49204887?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/viniaxt',
    html_url: 'https://github.com/viniaxt',
    followers_url: 'https://api.github.com/users/viniaxt/followers',
    following_url:
      'https://api.github.com/users/viniaxt/following{/other_user}',
    gists_url: 'https://api.github.com/users/viniaxt/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/viniaxt/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/viniaxt/subscriptions',
    organizations_url: 'https://api.github.com/users/viniaxt/orgs',
    repos_url: 'https://api.github.com/users/viniaxt/repos',
    events_url: 'https://api.github.com/users/viniaxt/events{/privacy}',
    received_events_url: 'https://api.github.com/users/viniaxt/received_events',
    type: 'User',
    site_admin: false,
    name: 'Vinicius Axt',
    company: 'FW7',
    blog: 'viniaxt',
    location: null,
    email: null,
    hireable: null,
    bio: null,
    public_repos: 6,
    public_gists: 0,
    followers: 1,
    following: 0,
    created_at: '2019-04-02T16:32:29Z',
    updated_at: '2019-07-14T15:26:48Z'
  },
  {
    login: 'Pablo75321',
    id: 53086031,
    node_id: 'MDQ6VXNlcjUzMDg2MDMx',
    avatar_url: 'https://avatars0.githubusercontent.com/u/53086031?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/Pablo75321',
    html_url: 'https://github.com/Pablo75321',
    followers_url: 'https://api.github.com/users/Pablo75321/followers',
    following_url:
      'https://api.github.com/users/Pablo75321/following{/other_user}',
    gists_url: 'https://api.github.com/users/Pablo75321/gists{/gist_id}',
    starred_url:
      'https://api.github.com/users/Pablo75321/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/Pablo75321/subscriptions',
    organizations_url: 'https://api.github.com/users/Pablo75321/orgs',
    repos_url: 'https://api.github.com/users/Pablo75321/repos',
    events_url: 'https://api.github.com/users/Pablo75321/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/Pablo75321/received_events',
    type: 'User',
    site_admin: false,
    name: 'Pablo_Danilo',
    company: null,
    blog: '',
    location: null,
    email: null,
    hireable: null,
    bio: null,
    public_repos: 0,
    public_gists: 0,
    followers: 0,
    following: 0,
    created_at: '2019-07-19T12:36:43Z',
    updated_at: '2019-07-22T23:48:23Z'
  }
]
